

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-sitemap

title: "Bridg Doc" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: "your.email@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
collections:
  docs:
    output: true
    permalink: /:collection/:name
markdown: kramdown
